// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-d80-Og1yuysP9ue8M9UMurytUj_5-UY',
    appId: '1:942816706006:web:0d923c042da27083c37877',
    messagingSenderId: '942816706006',
    projectId: 'taskflow-708dc',
    authDomain: 'taskflow-708dc.firebaseapp.com',
    storageBucket: 'taskflow-708dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRi4RO-X7yz8AJAar1GgOPDH2K_pXiCE',
    appId: '1:942816706006:android:9b25a5e84a51856bc37877',
    messagingSenderId: '942816706006',
    projectId: 'taskflow-708dc',
    storageBucket: 'taskflow-708dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBlRSuFiHhjhY0X5p89--azzvazEQ6Qqc',
    appId: '1:942816706006:ios:b659cbfaf5f0d061c37877',
    messagingSenderId: '942816706006',
    projectId: 'taskflow-708dc',
    storageBucket: 'taskflow-708dc.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBlRSuFiHhjhY0X5p89--azzvazEQ6Qqc',
    appId: '1:942816706006:ios:b659cbfaf5f0d061c37877',
    messagingSenderId: '942816706006',
    projectId: 'taskflow-708dc',
    storageBucket: 'taskflow-708dc.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-d80-Og1yuysP9ue8M9UMurytUj_5-UY',
    appId: '1:942816706006:web:7cf7f7e5692c2eb4c37877',
    messagingSenderId: '942816706006',
    projectId: 'taskflow-708dc',
    authDomain: 'taskflow-708dc.firebaseapp.com',
    storageBucket: 'taskflow-708dc.firebasestorage.app',
  );
}
